# The timezone of the robot location as a pytz timezone (https://pythonhosted.org/pytz/#helpers)
location_tz: America/Los_Angeles
# Connector log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_level: INFO
# The type of connector
connector_type: sick_tag_loc
# Update rate of the connector's main execution loop in Hz
update_freq: 5.0

# This is where you define custom fields specific to your robot's connector
connector_config:
  sick_rtls_http_server_address: http://192.168.1.249/
  sick_rtls_rest_api_port: 8080
  sick_rtls_websocket_port: 8080
